# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chassis_gui_v1.1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chassisGui(object):
    def setupUi(self, chassisGui):
        chassisGui.setObjectName("chassisGui")
        chassisGui.setWindowModality(QtCore.Qt.ApplicationModal)
        chassisGui.resize(700, 590)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/images/SPlogo_130x90(1naklejka).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        chassisGui.setWindowIcon(icon)
        chassisGui.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.centralwidget = QtWidgets.QWidget(chassisGui)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(200, 0, 491, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.pcModeLabel = QtWidgets.QLabel(self.frame_2)
        self.pcModeLabel.setGeometry(QtCore.QRect(100, 40, 71, 21))
        self.pcModeLabel.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.pcModeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.pcModeLabel.setLineWidth(2)
        self.pcModeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.pcModeLabel.setObjectName("pcModeLabel")
        self.arduinoModeLabel = QtWidgets.QLabel(self.frame_2)
        self.arduinoModeLabel.setGeometry(QtCore.QRect(100, 60, 71, 21))
        self.arduinoModeLabel.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.arduinoModeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.arduinoModeLabel.setLineWidth(2)
        self.arduinoModeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.arduinoModeLabel.setObjectName("arduinoModeLabel")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(180, 10, 71, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pcSpeedLabel = QtWidgets.QLabel(self.frame_2)
        self.pcSpeedLabel.setGeometry(QtCore.QRect(180, 40, 71, 21))
        self.pcSpeedLabel.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.pcSpeedLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.pcSpeedLabel.setLineWidth(2)
        self.pcSpeedLabel.setTextFormat(QtCore.Qt.AutoText)
        self.pcSpeedLabel.setObjectName("pcSpeedLabel")
        self.arduinoSpeedLabel = QtWidgets.QLabel(self.frame_2)
        self.arduinoSpeedLabel.setGeometry(QtCore.QRect(180, 60, 71, 21))
        self.arduinoSpeedLabel.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.arduinoSpeedLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.arduinoSpeedLabel.setLineWidth(2)
        self.arduinoSpeedLabel.setTextFormat(QtCore.Qt.AutoText)
        self.arduinoSpeedLabel.setObjectName("arduinoSpeedLabel")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(330, 20, 81, 17))
        self.label_14.setObjectName("label_14")
        self.guiPriorityLabelPc = QtWidgets.QLabel(self.frame_2)
        self.guiPriorityLabelPc.setGeometry(QtCore.QRect(270, 40, 71, 21))
        self.guiPriorityLabelPc.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.guiPriorityLabelPc.setFrameShape(QtWidgets.QFrame.Box)
        self.guiPriorityLabelPc.setLineWidth(2)
        self.guiPriorityLabelPc.setTextFormat(QtCore.Qt.AutoText)
        self.guiPriorityLabelPc.setObjectName("guiPriorityLabelPc")
        self.rcPriorityLabelPc = QtWidgets.QLabel(self.frame_2)
        self.rcPriorityLabelPc.setGeometry(QtCore.QRect(340, 40, 71, 21))
        self.rcPriorityLabelPc.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.rcPriorityLabelPc.setFrameShape(QtWidgets.QFrame.Box)
        self.rcPriorityLabelPc.setLineWidth(2)
        self.rcPriorityLabelPc.setTextFormat(QtCore.Qt.AutoText)
        self.rcPriorityLabelPc.setObjectName("rcPriorityLabelPc")
        self.padPriorityLabelPc = QtWidgets.QLabel(self.frame_2)
        self.padPriorityLabelPc.setGeometry(QtCore.QRect(410, 40, 71, 21))
        self.padPriorityLabelPc.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.padPriorityLabelPc.setFrameShape(QtWidgets.QFrame.Box)
        self.padPriorityLabelPc.setLineWidth(2)
        self.padPriorityLabelPc.setTextFormat(QtCore.Qt.AutoText)
        self.padPriorityLabelPc.setObjectName("padPriorityLabelPc")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.padPriorityLabelArduino = QtWidgets.QLabel(self.frame_2)
        self.padPriorityLabelArduino.setGeometry(QtCore.QRect(410, 60, 71, 21))
        self.padPriorityLabelArduino.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.padPriorityLabelArduino.setFrameShape(QtWidgets.QFrame.Box)
        self.padPriorityLabelArduino.setLineWidth(2)
        self.padPriorityLabelArduino.setTextFormat(QtCore.Qt.AutoText)
        self.padPriorityLabelArduino.setObjectName("padPriorityLabelArduino")
        self.guiPriorityLabelArduino = QtWidgets.QLabel(self.frame_2)
        self.guiPriorityLabelArduino.setGeometry(QtCore.QRect(270, 60, 71, 21))
        self.guiPriorityLabelArduino.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.guiPriorityLabelArduino.setFrameShape(QtWidgets.QFrame.Box)
        self.guiPriorityLabelArduino.setLineWidth(2)
        self.guiPriorityLabelArduino.setTextFormat(QtCore.Qt.AutoText)
        self.guiPriorityLabelArduino.setObjectName("guiPriorityLabelArduino")
        self.rcPriorityLabelArduino = QtWidgets.QLabel(self.frame_2)
        self.rcPriorityLabelArduino.setGeometry(QtCore.QRect(340, 60, 71, 21))
        self.rcPriorityLabelArduino.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.rcPriorityLabelArduino.setFrameShape(QtWidgets.QFrame.Box)
        self.rcPriorityLabelArduino.setLineWidth(2)
        self.rcPriorityLabelArduino.setTextFormat(QtCore.Qt.AutoText)
        self.rcPriorityLabelArduino.setObjectName("rcPriorityLabelArduino")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setGeometry(QtCore.QRect(100, 10, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 201, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setMidLineWidth(9)
        self.frame_3.setObjectName("frame_3")
        self.xboxControlRadio = QtWidgets.QRadioButton(self.frame_3)
        self.xboxControlRadio.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.xboxControlRadio.setObjectName("xboxControlRadio")
        self.guiControlRadio = QtWidgets.QRadioButton(self.frame_3)
        self.guiControlRadio.setGeometry(QtCore.QRect(10, 50, 151, 20))
        self.guiControlRadio.setObjectName("guiControlRadio")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.rcControlRadio = QtWidgets.QRadioButton(self.frame_3)
        self.rcControlRadio.setGeometry(QtCore.QRect(10, 70, 151, 20))
        self.rcControlRadio.setObjectName("rcControlRadio")
        self.drivingStrategyFrame = QtWidgets.QFrame(self.centralwidget)
        self.drivingStrategyFrame.setGeometry(QtCore.QRect(0, 100, 101, 181))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.drivingStrategyFrame.setPalette(palette)
        self.drivingStrategyFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.drivingStrategyFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.drivingStrategyFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.drivingStrategyFrame.setLineWidth(2)
        self.drivingStrategyFrame.setMidLineWidth(9)
        self.drivingStrategyFrame.setObjectName("drivingStrategyFrame")
        self.label_6 = QtWidgets.QLabel(self.drivingStrategyFrame)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 81, 51))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.rotaryModeRadio = QtWidgets.QRadioButton(self.drivingStrategyFrame)
        self.rotaryModeRadio.setGeometry(QtCore.QRect(10, 90, 81, 20))
        self.rotaryModeRadio.setObjectName("rotaryModeRadio")
        self.twistModeRadio = QtWidgets.QRadioButton(self.drivingStrategyFrame)
        self.twistModeRadio.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.twistModeRadio.setObjectName("twistModeRadio")
        self.tankModeRadio = QtWidgets.QRadioButton(self.drivingStrategyFrame)
        self.tankModeRadio.setGeometry(QtCore.QRect(10, 70, 61, 20))
        self.tankModeRadio.setObjectName("tankModeRadio")
        self.guiArmingCheck = QtWidgets.QCheckBox(self.drivingStrategyFrame)
        self.guiArmingCheck.setGeometry(QtCore.QRect(10, 140, 71, 23))
        self.guiArmingCheck.setObjectName("guiArmingCheck")
        self.angleLeftForwardLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.angleLeftForwardLabel.setGeometry(QtCore.QRect(280, 90, 64, 23))
        self.angleLeftForwardLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.angleLeftForwardLabel.setObjectName("angleLeftForwardLabel")
        self.velLeftForwardLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.velLeftForwardLabel.setGeometry(QtCore.QRect(280, 110, 64, 23))
        self.velLeftForwardLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.velLeftForwardLabel.setObjectName("velLeftForwardLabel")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(200, 90, 71, 21))
        self.label_11.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_11.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_11.setObjectName("label_11")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(220, 110, 51, 21))
        self.label_15.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_15.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_15.setObjectName("label_15")
        self.angleLeftRewardLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.angleLeftRewardLabel.setGeometry(QtCore.QRect(280, 300, 64, 23))
        self.angleLeftRewardLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.angleLeftRewardLabel.setObjectName("angleLeftRewardLabel")
        self.velLeftRewardLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.velLeftRewardLabel.setGeometry(QtCore.QRect(280, 280, 64, 23))
        self.velLeftRewardLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.velLeftRewardLabel.setObjectName("velLeftRewardLabel")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(220, 280, 51, 21))
        self.label_16.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_16.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(200, 300, 71, 21))
        self.label_17.setStyleSheet("background-color: rgba(255, 102, 0, 255);\n"
"")
        self.label_17.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_17.setObjectName("label_17")
        self.angleRightRewardLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.angleRightRewardLabel.setGeometry(QtCore.QRect(530, 300, 64, 23))
        self.angleRightRewardLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.angleRightRewardLabel.setObjectName("angleRightRewardLabel")
        self.velRightRewardLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.velRightRewardLabel.setGeometry(QtCore.QRect(530, 280, 64, 23))
        self.velRightRewardLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.velRightRewardLabel.setObjectName("velRightRewardLabel")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(600, 280, 51, 21))
        self.label_18.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_18.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(600, 300, 71, 21))
        self.label_19.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_19.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(600, 110, 51, 21))
        self.label_20.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_20.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_20.setObjectName("label_20")
        self.velRightForwardLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.velRightForwardLabel.setGeometry(QtCore.QRect(530, 110, 64, 23))
        self.velRightForwardLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.velRightForwardLabel.setObjectName("velRightForwardLabel")
        self.angleRightForwardLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.angleRightForwardLabel.setGeometry(QtCore.QRect(530, 90, 64, 23))
        self.angleRightForwardLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.angleRightForwardLabel.setObjectName("angleRightForwardLabel")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(600, 90, 71, 21))
        self.label_21.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_21.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_21.setObjectName("label_21")
        self.chassisLabel = QtWidgets.QLabel(self.centralwidget)
        self.chassisLabel.setGeometry(QtCore.QRect(350, 90, 171, 231))
        self.chassisLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.chassisLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.chassisLabel.setLineWidth(2)
        self.chassisLabel.setMidLineWidth(1)
        self.chassisLabel.setText("")
        self.chassisLabel.setPixmap(QtGui.QPixmap("Resources/images/podwozie6kol.png"))
        self.chassisLabel.setScaledContents(True)
        self.chassisLabel.setObjectName("chassisLabel")
        self.speedLevelFrame = QtWidgets.QFrame(self.centralwidget)
        self.speedLevelFrame.setGeometry(QtCore.QRect(100, 100, 101, 181))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.speedLevelFrame.setPalette(palette)
        self.speedLevelFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.speedLevelFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.speedLevelFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.speedLevelFrame.setLineWidth(2)
        self.speedLevelFrame.setMidLineWidth(9)
        self.speedLevelFrame.setObjectName("speedLevelFrame")
        self.label_10 = QtWidgets.QLabel(self.speedLevelFrame)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 61, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.turboSpeedRadio = QtWidgets.QRadioButton(self.speedLevelFrame)
        self.turboSpeedRadio.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.turboSpeedRadio.setObjectName("turboSpeedRadio")
        self.slowSpeedRadio = QtWidgets.QRadioButton(self.speedLevelFrame)
        self.slowSpeedRadio.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.slowSpeedRadio.setObjectName("slowSpeedRadio")
        self.fastSpeedRadio = QtWidgets.QRadioButton(self.speedLevelFrame)
        self.fastSpeedRadio.setGeometry(QtCore.QRect(10, 90, 71, 20))
        self.fastSpeedRadio.setObjectName("fastSpeedRadio")
        self.frameJoypad = QtWidgets.QFrame(self.centralwidget)
        self.frameJoypad.setGeometry(QtCore.QRect(440, 340, 251, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frameJoypad.setPalette(palette)
        self.frameJoypad.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.frameJoypad.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameJoypad.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameJoypad.setLineWidth(2)
        self.frameJoypad.setMidLineWidth(9)
        self.frameJoypad.setObjectName("frameJoypad")
        self.widget = QtWidgets.QWidget(self.frameJoypad)
        self.widget.setGeometry(QtCore.QRect(10, 10, 231, 179))
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 231, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(220, 200, 51, 21))
        self.label_27.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_27.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_27.setObjectName("label_27")
        self.velLeftCenterLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.velLeftCenterLabel.setGeometry(QtCore.QRect(280, 200, 64, 23))
        self.velLeftCenterLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.velLeftCenterLabel.setObjectName("velLeftCenterLabel")
        self.velRightCenterLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.velRightCenterLabel.setGeometry(QtCore.QRect(530, 200, 64, 23))
        self.velRightCenterLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.velRightCenterLabel.setObjectName("velRightCenterLabel")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(600, 200, 51, 21))
        self.label_28.setStyleSheet("background-color: rgba(255, 102, 0, 255);")
        self.label_28.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_28.setObjectName("label_28")
        self.xboxArmedFrame = QtWidgets.QFrame(self.centralwidget)
        self.xboxArmedFrame.setGeometry(QtCore.QRect(0, 330, 248, 211))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.xboxArmedFrame.setPalette(palette)
        self.xboxArmedFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.xboxArmedFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.xboxArmedFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.xboxArmedFrame.setLineWidth(2)
        self.xboxArmedFrame.setMidLineWidth(9)
        self.xboxArmedFrame.setObjectName("xboxArmedFrame")
        self.progressBarY = QtWidgets.QProgressBar(self.xboxArmedFrame)
        self.progressBarY.setGeometry(QtCore.QRect(50, 70, 118, 23))
        self.progressBarY.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.progressBarY.setProperty("value", 0)
        self.progressBarY.setObjectName("progressBarY")
        self.progressBarX = QtWidgets.QProgressBar(self.xboxArmedFrame)
        self.progressBarX.setGeometry(QtCore.QRect(50, 40, 118, 23))
        self.progressBarX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.progressBarX.setProperty("value", 0)
        self.progressBarX.setObjectName("progressBarX")
        self.armedStatusLabel = QtWidgets.QLabel(self.xboxArmedFrame)
        self.armedStatusLabel.setGeometry(QtCore.QRect(170, 40, 71, 21))
        self.armedStatusLabel.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.armedStatusLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.armedStatusLabel.setLineWidth(2)
        self.armedStatusLabel.setTextFormat(QtCore.Qt.AutoText)
        self.armedStatusLabel.setObjectName("armedStatusLabel")
        self.label_13 = QtWidgets.QLabel(self.xboxArmedFrame)
        self.label_13.setGeometry(QtCore.QRect(20, 70, 21, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.xboxArmedFrame)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 21, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_22 = QtWidgets.QLabel(self.xboxArmedFrame)
        self.label_22.setGeometry(QtCore.QRect(170, 10, 71, 21))
        self.label_22.setStyleSheet("background-color: rgba(255, 102, 0, 255);\n"
"")
        self.label_22.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.xboxArmedFrame)
        self.label_23.setGeometry(QtCore.QRect(20, 10, 121, 17))
        self.label_23.setObjectName("label_23")
        self.padVelocity = QtWidgets.QLCDNumber(self.xboxArmedFrame)
        self.padVelocity.setGeometry(QtCore.QRect(100, 120, 64, 23))
        self.padVelocity.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.padVelocity.setObjectName("padVelocity")
        self.padTurnRatio = QtWidgets.QLCDNumber(self.xboxArmedFrame)
        self.padTurnRatio.setGeometry(QtCore.QRect(100, 160, 64, 23))
        self.padTurnRatio.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.padTurnRatio.setObjectName("padTurnRatio")
        self.label_24 = QtWidgets.QLabel(self.xboxArmedFrame)
        self.label_24.setGeometry(QtCore.QRect(20, 130, 61, 17))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.xboxArmedFrame)
        self.label_25.setGeometry(QtCore.QRect(20, 160, 71, 17))
        self.label_25.setObjectName("label_25")
        self.joypadArmedFrame = QtWidgets.QFrame(self.centralwidget)
        self.joypadArmedFrame.setGeometry(QtCore.QRect(190, 340, 251, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.joypadArmedFrame.setPalette(palette)
        self.joypadArmedFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.joypadArmedFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.joypadArmedFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.joypadArmedFrame.setLineWidth(2)
        self.joypadArmedFrame.setMidLineWidth(9)
        self.joypadArmedFrame.setObjectName("joypadArmedFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.joypadArmedFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_32 = QtWidgets.QLabel(self.joypadArmedFrame)
        self.label_32.setStyleSheet("background-color: rgba(255, 102, 0, 255);\n"
"")
        self.label_32.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.joypadArmedFrame)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 0, 1, 1, 2)
        self.joypadArmedStatusLabel = QtWidgets.QLabel(self.joypadArmedFrame)
        self.joypadArmedStatusLabel.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.joypadArmedStatusLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.joypadArmedStatusLabel.setLineWidth(2)
        self.joypadArmedStatusLabel.setTextFormat(QtCore.Qt.AutoText)
        self.joypadArmedStatusLabel.setObjectName("joypadArmedStatusLabel")
        self.gridLayout_2.addWidget(self.joypadArmedStatusLabel, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.joypadArmedFrame)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 1, 1, 1, 1)
        self.joypadVelocity = QtWidgets.QLCDNumber(self.joypadArmedFrame)
        self.joypadVelocity.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.joypadVelocity.setObjectName("joypadVelocity")
        self.gridLayout_2.addWidget(self.joypadVelocity, 1, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.joypadArmedFrame)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 2, 1, 1, 1)
        self.joypadTurnRatio = QtWidgets.QLCDNumber(self.joypadArmedFrame)
        self.joypadTurnRatio.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.joypadTurnRatio.setObjectName("joypadTurnRatio")
        self.gridLayout_2.addWidget(self.joypadTurnRatio, 2, 2, 1, 1)
        chassisGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(chassisGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        chassisGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(chassisGui)
        self.statusbar.setObjectName("statusbar")
        chassisGui.setStatusBar(self.statusbar)

        self.retranslateUi(chassisGui)
        QtCore.QMetaObject.connectSlotsByName(chassisGui)

    def retranslateUi(self, chassisGui):
        _translate = QtCore.QCoreApplication.translate
        chassisGui.setWindowTitle(_translate("chassisGui", "Chassis Panel"))
        self.pcModeLabel.setText(_translate("chassisGui", "N/A"))
        self.arduinoModeLabel.setText(_translate("chassisGui", "N/A"))
        self.label_12.setText(_translate("chassisGui", "<html><head/><body><p align=\"center\">SPEED<br/>LEVEL</p></body></html>"))
        self.pcSpeedLabel.setText(_translate("chassisGui", "N/A"))
        self.arduinoSpeedLabel.setText(_translate("chassisGui", "N/A"))
        self.label_14.setText(_translate("chassisGui", "PRIORITY:"))
        self.guiPriorityLabelPc.setText(_translate("chassisGui", "GUI"))
        self.rcPriorityLabelPc.setText(_translate("chassisGui", "RC"))
        self.padPriorityLabelPc.setText(_translate("chassisGui", "PAD"))
        self.label_7.setText(_translate("chassisGui", "CONTROL"))
        self.label_8.setText(_translate("chassisGui", "ARDUINO"))
        self.padPriorityLabelArduino.setText(_translate("chassisGui", "PAD"))
        self.guiPriorityLabelArduino.setText(_translate("chassisGui", "GUI"))
        self.rcPriorityLabelArduino.setText(_translate("chassisGui", "RC"))
        self.label_29.setText(_translate("chassisGui", "<html><head/><body><p>DRIVING<br/>STRATEGY</p></body></html>"))
        self.label_30.setText(_translate("chassisGui", "STATE"))
        self.xboxControlRadio.setText(_translate("chassisGui", "XBOX PAD CONTROL"))
        self.guiControlRadio.setText(_translate("chassisGui", "GUI CONTROL"))
        self.label_26.setText(_translate("chassisGui", "CONTROL CHOICE"))
        self.rcControlRadio.setText(_translate("chassisGui", "RC CONTROL"))
        self.label_6.setText(_translate("chassisGui", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">DRIVING<br/>STRATEGY<br/>SELECT</span></p></body></html>"))
        self.rotaryModeRadio.setText(_translate("chassisGui", "ROTARY"))
        self.twistModeRadio.setText(_translate("chassisGui", "TWIST"))
        self.tankModeRadio.setText(_translate("chassisGui", "TANK"))
        self.guiArmingCheck.setText(_translate("chassisGui", "Arming"))
        self.label_11.setText(_translate("chassisGui", "Angle [°]"))
        self.label_15.setText(_translate("chassisGui", "[m/s]"))
        self.label_16.setText(_translate("chassisGui", "[m/s]"))
        self.label_17.setText(_translate("chassisGui", "Angle [°]"))
        self.label_18.setText(_translate("chassisGui", "[m/s]"))
        self.label_19.setText(_translate("chassisGui", "Angle [°]"))
        self.label_20.setText(_translate("chassisGui", "[m/s]"))
        self.label_21.setText(_translate("chassisGui", "Angle [°]"))
        self.label_10.setText(_translate("chassisGui", "<html><head/><body><p align=\"center\">SPEED<br/>LEVEL<br/>MODE</p></body></html>"))
        self.turboSpeedRadio.setText(_translate("chassisGui", "TURBO"))
        self.slowSpeedRadio.setText(_translate("chassisGui", "SLOW"))
        self.fastSpeedRadio.setText(_translate("chassisGui", "FAST"))
        self.label_27.setText(_translate("chassisGui", "[m/s]"))
        self.label_28.setText(_translate("chassisGui", "[m/s]"))
        self.armedStatusLabel.setText(_translate("chassisGui", "N/A"))
        self.label_13.setText(_translate("chassisGui", "Y"))
        self.label_9.setText(_translate("chassisGui", "X"))
        self.label_22.setText(_translate("chassisGui", "Status"))
        self.label_23.setText(_translate("chassisGui", "PAD LOG"))
        self.label_24.setText(_translate("chassisGui", "Velocity"))
        self.label_25.setText(_translate("chassisGui", "Turn ratio"))
        self.label_32.setText(_translate("chassisGui", "Status"))
        self.label_33.setText(_translate("chassisGui", "JOYPAD LOG"))
        self.joypadArmedStatusLabel.setText(_translate("chassisGui", "N/A"))
        self.label_34.setText(_translate("chassisGui", "Velocity"))
        self.label_35.setText(_translate("chassisGui", "Turn ratio"))
