# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'containers_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_containersUi(object):
    def setupUi(self, containersUi):
        containersUi.setObjectName("containersUi")
        containersUi.resize(483, 177)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/SPlogo_130x90(1naklejka).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        containersUi.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(containersUi)
        self.centralwidget.setObjectName("centralwidget")
        self.firstContainerOpen = QtWidgets.QPushButton(self.centralwidget)
        self.firstContainerOpen.setGeometry(QtCore.QRect(50, 20, 51, 25))
        self.firstContainerOpen.setObjectName("firstContainerOpen")
        self.firstContainerClose = QtWidgets.QPushButton(self.centralwidget)
        self.firstContainerClose.setGeometry(QtCore.QRect(120, 20, 51, 25))
        self.firstContainerClose.setObjectName("firstContainerClose")
        self.secondContainerOpen = QtWidgets.QPushButton(self.centralwidget)
        self.secondContainerOpen.setGeometry(QtCore.QRect(50, 60, 51, 25))
        self.secondContainerOpen.setObjectName("secondContainerOpen")
        self.thirdContainerOpen = QtWidgets.QPushButton(self.centralwidget)
        self.thirdContainerOpen.setGeometry(QtCore.QRect(50, 100, 51, 25))
        self.thirdContainerOpen.setObjectName("thirdContainerOpen")
        self.secondContainerClose = QtWidgets.QPushButton(self.centralwidget)
        self.secondContainerClose.setGeometry(QtCore.QRect(120, 60, 51, 25))
        self.secondContainerClose.setObjectName("secondContainerClose")
        self.thirdContainerClose = QtWidgets.QPushButton(self.centralwidget)
        self.thirdContainerClose.setGeometry(QtCore.QRect(120, 100, 51, 25))
        self.thirdContainerClose.setObjectName("thirdContainerClose")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 31, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 31, 21))
        self.label_3.setObjectName("label_3")
        self.firstContainerMeasurement = QtWidgets.QLCDNumber(self.centralwidget)
        self.firstContainerMeasurement.setGeometry(QtCore.QRect(220, 20, 64, 23))
        self.firstContainerMeasurement.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(238, 238, 236);")
        self.firstContainerMeasurement.setObjectName("firstContainerMeasurement")
        self.secondContainerMeasurement = QtWidgets.QLCDNumber(self.centralwidget)
        self.secondContainerMeasurement.setGeometry(QtCore.QRect(220, 60, 64, 23))
        self.secondContainerMeasurement.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(238, 238, 236);")
        self.secondContainerMeasurement.setObjectName("secondContainerMeasurement")
        self.thirdContainerMeasurement = QtWidgets.QLCDNumber(self.centralwidget)
        self.thirdContainerMeasurement.setGeometry(QtCore.QRect(220, 100, 64, 23))
        self.thirdContainerMeasurement.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(238, 238, 236);")
        self.thirdContainerMeasurement.setObjectName("thirdContainerMeasurement")
        self.firstCalibrationValue = QtWidgets.QLineEdit(self.centralwidget)
        self.firstCalibrationValue.setGeometry(QtCore.QRect(320, 20, 113, 25))
        self.firstCalibrationValue.setObjectName("firstCalibrationValue")
        self.secondCalibrationValue = QtWidgets.QLineEdit(self.centralwidget)
        self.secondCalibrationValue.setGeometry(QtCore.QRect(320, 60, 113, 25))
        self.secondCalibrationValue.setObjectName("secondCalibrationValue")
        self.thirdCalibrationValue = QtWidgets.QLineEdit(self.centralwidget)
        self.thirdCalibrationValue.setGeometry(QtCore.QRect(320, 100, 113, 25))
        self.thirdCalibrationValue.setObjectName("thirdCalibrationValue")
        self.firstCalibrationSend = QtWidgets.QPushButton(self.centralwidget)
        self.firstCalibrationSend.setGeometry(QtCore.QRect(440, 20, 41, 25))
        self.firstCalibrationSend.setObjectName("firstCalibrationSend")
        self.secondCalibrationSend = QtWidgets.QPushButton(self.centralwidget)
        self.secondCalibrationSend.setGeometry(QtCore.QRect(440, 60, 41, 25))
        self.secondCalibrationSend.setObjectName("secondCalibrationSend")
        self.thirdCalibrationSend = QtWidgets.QPushButton(self.centralwidget)
        self.thirdCalibrationSend.setGeometry(QtCore.QRect(440, 100, 41, 25))
        self.thirdCalibrationSend.setObjectName("thirdCalibrationSend")
        self.indicatorOne = QtWidgets.QLabel(self.centralwidget)
        self.indicatorOne.setGeometry(QtCore.QRect(190, 20, 21, 21))
        self.indicatorOne.setText("")
        self.indicatorOne.setPixmap(QtGui.QPixmap("resources/images/circle_green.svg"))
        self.indicatorOne.setScaledContents(True)
        self.indicatorOne.setObjectName("indicatorOne")
        self.indicatorTwo = QtWidgets.QLabel(self.centralwidget)
        self.indicatorTwo.setGeometry(QtCore.QRect(190, 60, 21, 21))
        self.indicatorTwo.setText("")
        self.indicatorTwo.setPixmap(QtGui.QPixmap("resources/images/circle_green.svg"))
        self.indicatorTwo.setScaledContents(True)
        self.indicatorTwo.setObjectName("indicatorTwo")
        self.indicatorThree = QtWidgets.QLabel(self.centralwidget)
        self.indicatorThree.setGeometry(QtCore.QRect(190, 100, 21, 21))
        self.indicatorThree.setText("")
        self.indicatorThree.setPixmap(QtGui.QPixmap("resources/images/circle_green.svg"))
        self.indicatorThree.setScaledContents(True)
        self.indicatorThree.setObjectName("indicatorThree")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 20, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 60, 31, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 100, 31, 21))
        self.label_6.setObjectName("label_6")
        containersUi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(containersUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 22))
        self.menubar.setObjectName("menubar")
        containersUi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(containersUi)
        self.statusbar.setObjectName("statusbar")
        containersUi.setStatusBar(self.statusbar)

        self.retranslateUi(containersUi)
        QtCore.QMetaObject.connectSlotsByName(containersUi)

    def retranslateUi(self, containersUi):
        _translate = QtCore.QCoreApplication.translate
        containersUi.setWindowTitle(_translate("containersUi", "Containers"))
        self.firstContainerOpen.setText(_translate("containersUi", "Open"))
        self.firstContainerClose.setText(_translate("containersUi", "Close"))
        self.secondContainerOpen.setText(_translate("containersUi", "Open"))
        self.thirdContainerOpen.setText(_translate("containersUi", "Open"))
        self.secondContainerClose.setText(_translate("containersUi", "Close"))
        self.thirdContainerClose.setText(_translate("containersUi", "Close"))
        self.label.setText(_translate("containersUi", "1st"))
        self.label_2.setText(_translate("containersUi", "2nd"))
        self.label_3.setText(_translate("containersUi", "3rd"))
        self.firstCalibrationSend.setText(_translate("containersUi", "Send"))
        self.secondCalibrationSend.setText(_translate("containersUi", "Send"))
        self.thirdCalibrationSend.setText(_translate("containersUi", "Send"))
        self.label_4.setText(_translate("containersUi", "[ g ]"))
        self.label_5.setText(_translate("containersUi", "[ g ]"))
        self.label_6.setText(_translate("containersUi", "[ g ]"))
