# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manipulator_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manipulatorGui(object):
    def setupUi(self, manipulatorGui):
        manipulatorGui.setObjectName("manipulatorGui")
        manipulatorGui.setWindowModality(QtCore.Qt.ApplicationModal)
        manipulatorGui.resize(715, 469)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/SPlogo_130x90(1naklejka).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        manipulatorGui.setWindowIcon(icon)
        manipulatorGui.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(manipulatorGui)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 181, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setMidLineWidth(9)
        self.frame_3.setObjectName("frame_3")
        self.mouseControlRadio = QtWidgets.QRadioButton(self.frame_3)
        self.mouseControlRadio.setGeometry(QtCore.QRect(10, 40, 161, 20))
        self.mouseControlRadio.setObjectName("mouseControlRadio")
        self.positionSendingRadio = QtWidgets.QRadioButton(self.frame_3)
        self.positionSendingRadio.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.positionSendingRadio.setObjectName("positionSendingRadio")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 70, 181, 231))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_4.setPalette(palette)
        self.frame_4.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setMidLineWidth(9)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_24 = QtWidgets.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(100, 40, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setGeometry(QtCore.QRect(8, 100, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.closeGripperButton = QtWidgets.QPushButton(self.frame_4)
        self.closeGripperButton.setGeometry(QtCore.QRect(20, 60, 31, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeGripperButton.setFont(font)
        self.closeGripperButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.closeGripperButton.setObjectName("closeGripperButton")
        self.openGripperButton = QtWidgets.QPushButton(self.frame_4)
        self.openGripperButton.setGeometry(QtCore.QRect(100, 60, 31, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.openGripperButton.setFont(font)
        self.openGripperButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.openGripperButton.setObjectName("openGripperButton")
        self.commandSendButton = QtWidgets.QPushButton(self.frame_4)
        self.commandSendButton.setGeometry(QtCore.QRect(120, 100, 51, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.commandSendButton.setFont(font)
        self.commandSendButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.commandSendButton.setObjectName("commandSendButton")
        self.distanceLcd = QtWidgets.QLCDNumber(self.frame_4)
        self.distanceLcd.setGeometry(QtCore.QRect(10, 130, 61, 23))
        self.distanceLcd.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.distanceLcd.setObjectName("distanceLcd")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(80, 130, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.encoderLcd = QtWidgets.QLCDNumber(self.frame_4)
        self.encoderLcd.setGeometry(QtCore.QRect(10, 160, 61, 23))
        self.encoderLcd.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.encoderLcd.setObjectName("encoderLcd")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(80, 160, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.forceLcd = QtWidgets.QLCDNumber(self.frame_4)
        self.forceLcd.setGeometry(QtCore.QRect(10, 190, 61, 23))
        self.forceLcd.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.forceLcd.setObjectName("forceLcd")
        self.FORCE = QtWidgets.QLabel(self.frame_4)
        self.FORCE.setGeometry(QtCore.QRect(80, 190, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.FORCE.setFont(font)
        self.FORCE.setAlignment(QtCore.Qt.AlignCenter)
        self.FORCE.setObjectName("FORCE")
        self.positionFrame = QtWidgets.QFrame(self.centralwidget)
        self.positionFrame.setGeometry(QtCore.QRect(180, 0, 221, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.positionFrame.setPalette(palette)
        self.positionFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.positionFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.positionFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.positionFrame.setLineWidth(2)
        self.positionFrame.setMidLineWidth(9)
        self.positionFrame.setObjectName("positionFrame")
        self.label_8 = QtWidgets.QLabel(self.positionFrame)
        self.label_8.setGeometry(QtCore.QRect(10, 16, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.positionFrame)
        self.label.setGeometry(QtCore.QRect(20, 50, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.firstAxisLine = QtWidgets.QLineEdit(self.positionFrame)
        self.firstAxisLine.setGeometry(QtCore.QRect(60, 50, 51, 21))
        self.firstAxisLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.firstAxisLine.setObjectName("firstAxisLine")
        self.firstAxisManipButton = QtWidgets.QPushButton(self.positionFrame)
        self.firstAxisManipButton.setGeometry(QtCore.QRect(130, 50, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.firstAxisManipButton.setFont(font)
        self.firstAxisManipButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.firstAxisManipButton.setObjectName("firstAxisManipButton")
        self.secondAxisLine = QtWidgets.QLineEdit(self.positionFrame)
        self.secondAxisLine.setGeometry(QtCore.QRect(60, 80, 51, 21))
        self.secondAxisLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.secondAxisLine.setObjectName("secondAxisLine")
        self.secondAxisManipButton = QtWidgets.QPushButton(self.positionFrame)
        self.secondAxisManipButton.setGeometry(QtCore.QRect(130, 80, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.secondAxisManipButton.setFont(font)
        self.secondAxisManipButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.secondAxisManipButton.setObjectName("secondAxisManipButton")
        self.label_2 = QtWidgets.QLabel(self.positionFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.thirdAxisLine = QtWidgets.QLineEdit(self.positionFrame)
        self.thirdAxisLine.setGeometry(QtCore.QRect(60, 110, 51, 21))
        self.thirdAxisLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.thirdAxisLine.setObjectName("thirdAxisLine")
        self.thirdAxisManipButton = QtWidgets.QPushButton(self.positionFrame)
        self.thirdAxisManipButton.setGeometry(QtCore.QRect(130, 110, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.thirdAxisManipButton.setFont(font)
        self.thirdAxisManipButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.thirdAxisManipButton.setObjectName("thirdAxisManipButton")
        self.label_3 = QtWidgets.QLabel(self.positionFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.fourthAxisLine = QtWidgets.QLineEdit(self.positionFrame)
        self.fourthAxisLine.setGeometry(QtCore.QRect(60, 140, 51, 21))
        self.fourthAxisLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fourthAxisLine.setObjectName("fourthAxisLine")
        self.fourthAxisManipButton = QtWidgets.QPushButton(self.positionFrame)
        self.fourthAxisManipButton.setGeometry(QtCore.QRect(130, 140, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fourthAxisManipButton.setFont(font)
        self.fourthAxisManipButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.fourthAxisManipButton.setObjectName("fourthAxisManipButton")
        self.label_4 = QtWidgets.QLabel(self.positionFrame)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.fifthAxisLine = QtWidgets.QLineEdit(self.positionFrame)
        self.fifthAxisLine.setGeometry(QtCore.QRect(60, 170, 51, 21))
        self.fifthAxisLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fifthAxisLine.setObjectName("fifthAxisLine")
        self.fifthAxisManipButton = QtWidgets.QPushButton(self.positionFrame)
        self.fifthAxisManipButton.setGeometry(QtCore.QRect(130, 170, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fifthAxisManipButton.setFont(font)
        self.fifthAxisManipButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.fifthAxisManipButton.setObjectName("fifthAxisManipButton")
        self.label_5 = QtWidgets.QLabel(self.positionFrame)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 0, 311, 371))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("resources/images/Manipulator.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.mouseFrame = QtWidgets.QFrame(self.centralwidget)
        self.mouseFrame.setGeometry(QtCore.QRect(180, 200, 221, 221))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mouseFrame.setPalette(palette)
        self.mouseFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.mouseFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.mouseFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mouseFrame.setLineWidth(2)
        self.mouseFrame.setMidLineWidth(9)
        self.mouseFrame.setObjectName("mouseFrame")
        self.label_10 = QtWidgets.QLabel(self.mouseFrame)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.mouseFrame)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.mouseFrame)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.mouseFrame)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.mouseFrame)
        self.label_16.setGeometry(QtCore.QRect(10, 160, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.mouseFrame)
        self.label_17.setGeometry(QtCore.QRect(10, 190, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_26 = QtWidgets.QLabel(self.mouseFrame)
        self.label_26.setGeometry(QtCore.QRect(40, 70, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.mouseFrame)
        self.label_27.setGeometry(QtCore.QRect(160, 70, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.mouseFrame)
        self.label_28.setGeometry(QtCore.QRect(160, 100, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.mouseFrame)
        self.label_29.setGeometry(QtCore.QRect(40, 100, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.mouseFrame)
        self.label_30.setGeometry(QtCore.QRect(160, 130, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.mouseFrame)
        self.label_31.setGeometry(QtCore.QRect(40, 130, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.mouseFrame)
        self.label_32.setGeometry(QtCore.QRect(160, 160, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.mouseFrame)
        self.label_33.setGeometry(QtCore.QRect(40, 160, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.mouseFrame)
        self.label_34.setGeometry(QtCore.QRect(160, 190, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.mouseFrame)
        self.label_35.setGeometry(QtCore.QRect(40, 190, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.firstAxisDisplay = QtWidgets.QLCDNumber(self.mouseFrame)
        self.firstAxisDisplay.setGeometry(QtCore.QRect(90, 70, 61, 23))
        self.firstAxisDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.firstAxisDisplay.setObjectName("firstAxisDisplay")
        self.secondAxisDisplay = QtWidgets.QLCDNumber(self.mouseFrame)
        self.secondAxisDisplay.setGeometry(QtCore.QRect(90, 100, 61, 23))
        self.secondAxisDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.secondAxisDisplay.setObjectName("secondAxisDisplay")
        self.thirdAxisDisplay = QtWidgets.QLCDNumber(self.mouseFrame)
        self.thirdAxisDisplay.setGeometry(QtCore.QRect(90, 130, 61, 23))
        self.thirdAxisDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.thirdAxisDisplay.setObjectName("thirdAxisDisplay")
        self.fourthAxisDisplay = QtWidgets.QLCDNumber(self.mouseFrame)
        self.fourthAxisDisplay.setGeometry(QtCore.QRect(90, 160, 61, 23))
        self.fourthAxisDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.fourthAxisDisplay.setObjectName("fourthAxisDisplay")
        self.fifthAxisDisplay = QtWidgets.QLCDNumber(self.mouseFrame)
        self.fifthAxisDisplay.setGeometry(QtCore.QRect(90, 190, 61, 23))
        self.fifthAxisDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.fifthAxisDisplay.setObjectName("fifthAxisDisplay")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(0, 300, 181, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_7.setPalette(palette)
        self.frame_7.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(2)
        self.frame_7.setMidLineWidth(9)
        self.frame_7.setObjectName("frame_7")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.activeAxisDisplay = QtWidgets.QLCDNumber(self.frame_7)
        self.activeAxisDisplay.setGeometry(QtCore.QRect(30, 40, 111, 61))
        self.activeAxisDisplay.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.activeAxisDisplay.setObjectName("activeAxisDisplay")
        manipulatorGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(manipulatorGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 22))
        self.menubar.setObjectName("menubar")
        manipulatorGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(manipulatorGui)
        self.statusbar.setObjectName("statusbar")
        manipulatorGui.setStatusBar(self.statusbar)

        self.retranslateUi(manipulatorGui)
        QtCore.QMetaObject.connectSlotsByName(manipulatorGui)

    def retranslateUi(self, manipulatorGui):
        _translate = QtCore.QCoreApplication.translate
        manipulatorGui.setWindowTitle(_translate("manipulatorGui", "Manipulator"))
        self.mouseControlRadio.setText(_translate("manipulatorGui", "3D mouse control"))
        self.positionSendingRadio.setText(_translate("manipulatorGui", "Position sending"))
        self.label_6.setText(_translate("manipulatorGui", "GRIPPER"))
        self.label_13.setText(_translate("manipulatorGui", "-"))
        self.label_24.setText(_translate("manipulatorGui", "+"))
        self.comboBox.setItemText(0, _translate("manipulatorGui", "RESET"))
        self.comboBox.setItemText(1, _translate("manipulatorGui", "STRONG GRIP"))
        self.comboBox.setItemText(2, _translate("manipulatorGui", "WEAK GRIP"))
        self.comboBox.setItemText(3, _translate("manipulatorGui", "VOLTAGE MEASURE"))
        self.comboBox.setItemText(4, _translate("manipulatorGui", "OPENLY"))
        self.comboBox.setItemText(5, _translate("manipulatorGui", "ENCODER POS"))
        self.comboBox.setItemText(6, _translate("manipulatorGui", "BEAM RESET"))
        self.closeGripperButton.setText(_translate("manipulatorGui", "<"))
        self.openGripperButton.setText(_translate("manipulatorGui", ">"))
        self.commandSendButton.setText(_translate("manipulatorGui", "SEND"))
        self.label_14.setText(_translate("manipulatorGui", "DISTANCE"))
        self.label_19.setText(_translate("manipulatorGui", "ENCODER"))
        self.FORCE.setText(_translate("manipulatorGui", "FORCE"))
        self.label_8.setText(_translate("manipulatorGui", "POSITION CONTROL"))
        self.label.setText(_translate("manipulatorGui", "1st"))
        self.firstAxisManipButton.setText(_translate("manipulatorGui", "SEND"))
        self.secondAxisManipButton.setText(_translate("manipulatorGui", "SEND"))
        self.label_2.setText(_translate("manipulatorGui", "2nd"))
        self.thirdAxisManipButton.setText(_translate("manipulatorGui", "SEND"))
        self.label_3.setText(_translate("manipulatorGui", "3rd"))
        self.fourthAxisManipButton.setText(_translate("manipulatorGui", "SEND"))
        self.label_4.setText(_translate("manipulatorGui", "4th"))
        self.fifthAxisManipButton.setText(_translate("manipulatorGui", "SEND"))
        self.label_5.setText(_translate("manipulatorGui", "5th"))
        self.label_10.setText(_translate("manipulatorGui", "3D Mouse Control"))
        self.label_11.setText(_translate("manipulatorGui", "1st"))
        self.label_12.setText(_translate("manipulatorGui", "2nd"))
        self.label_15.setText(_translate("manipulatorGui", "3rd"))
        self.label_16.setText(_translate("manipulatorGui", "4th"))
        self.label_17.setText(_translate("manipulatorGui", "5th"))
        self.label_26.setText(_translate("manipulatorGui", "-180"))
        self.label_27.setText(_translate("manipulatorGui", "+180"))
        self.label_28.setText(_translate("manipulatorGui", "+75"))
        self.label_29.setText(_translate("manipulatorGui", "0"))
        self.label_30.setText(_translate("manipulatorGui", "+135"))
        self.label_31.setText(_translate("manipulatorGui", "0"))
        self.label_32.setText(_translate("manipulatorGui", "+90"))
        self.label_33.setText(_translate("manipulatorGui", "-90"))
        self.label_34.setText(_translate("manipulatorGui", "+180"))
        self.label_35.setText(_translate("manipulatorGui", "-180"))
        self.label_18.setText(_translate("manipulatorGui", "Actual Active Axis"))
