# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'probe_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_probeGui(object):
    def setupUi(self, probeGui):
        probeGui.setObjectName("probeGui")
        probeGui.setWindowModality(QtCore.Qt.ApplicationModal)
        probeGui.resize(520, 464)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/SPlogo_130x90(1naklejka).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        probeGui.setWindowIcon(icon)
        probeGui.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(probeGui)
        self.centralwidget.setObjectName("centralwidget")
        self.controlFrame = QtWidgets.QFrame(self.centralwidget)
        self.controlFrame.setGeometry(QtCore.QRect(0, 0, 161, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.controlFrame.setPalette(palette)
        self.controlFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.controlFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.controlFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.controlFrame.setLineWidth(2)
        self.controlFrame.setMidLineWidth(9)
        self.controlFrame.setObjectName("controlFrame")
        self.manualControlRadio = QtWidgets.QRadioButton(self.controlFrame)
        self.manualControlRadio.setGeometry(QtCore.QRect(10, 40, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.manualControlRadio.setFont(font)
        self.manualControlRadio.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(77, 77, 77);")
        self.manualControlRadio.setObjectName("manualControlRadio")
        self.autoControlRadio = QtWidgets.QRadioButton(self.controlFrame)
        self.autoControlRadio.setGeometry(QtCore.QRect(10, 10, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.autoControlRadio.setFont(font)
        self.autoControlRadio.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"border-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.autoControlRadio.setObjectName("autoControlRadio")
        self.autoFrame = QtWidgets.QFrame(self.centralwidget)
        self.autoFrame.setGeometry(QtCore.QRect(160, 0, 361, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.autoFrame.setPalette(palette)
        self.autoFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.autoFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.autoFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.autoFrame.setLineWidth(2)
        self.autoFrame.setMidLineWidth(9)
        self.autoFrame.setObjectName("autoFrame")
        self.label_8 = QtWidgets.QLabel(self.autoFrame)
        self.label_8.setGeometry(QtCore.QRect(9, 16, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.startCycleButton = QtWidgets.QPushButton(self.autoFrame)
        self.startCycleButton.setGeometry(QtCore.QRect(90, 120, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startCycleButton.setFont(font)
        self.startCycleButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.startCycleButton.setObjectName("startCycleButton")
        self.stopCycleButton = QtWidgets.QPushButton(self.autoFrame)
        self.stopCycleButton.setGeometry(QtCore.QRect(220, 120, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stopCycleButton.setFont(font)
        self.stopCycleButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.stopCycleButton.setObjectName("stopCycleButton")
        self.stateOneLabel = QtWidgets.QLabel(self.autoFrame)
        self.stateOneLabel.setGeometry(QtCore.QRect(0, 160, 61, 31))
        self.stateOneLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.stateOneLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.stateOneLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stateOneLabel.setLineWidth(2)
        self.stateOneLabel.setObjectName("stateOneLabel")
        self.stateTwoLabel = QtWidgets.QLabel(self.autoFrame)
        self.stateTwoLabel.setGeometry(QtCore.QRect(60, 160, 61, 31))
        self.stateTwoLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.stateTwoLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.stateTwoLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stateTwoLabel.setLineWidth(2)
        self.stateTwoLabel.setObjectName("stateTwoLabel")
        self.stateThreeLabel = QtWidgets.QLabel(self.autoFrame)
        self.stateThreeLabel.setGeometry(QtCore.QRect(120, 160, 61, 31))
        self.stateThreeLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.stateThreeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.stateThreeLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stateThreeLabel.setLineWidth(2)
        self.stateThreeLabel.setObjectName("stateThreeLabel")
        self.stateFourLabel = QtWidgets.QLabel(self.autoFrame)
        self.stateFourLabel.setGeometry(QtCore.QRect(180, 160, 61, 31))
        self.stateFourLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.stateFourLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.stateFourLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stateFourLabel.setLineWidth(2)
        self.stateFourLabel.setObjectName("stateFourLabel")
        self.stateFiveLabel = QtWidgets.QLabel(self.autoFrame)
        self.stateFiveLabel.setGeometry(QtCore.QRect(240, 160, 61, 31))
        self.stateFiveLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.stateFiveLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.stateFiveLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stateFiveLabel.setLineWidth(2)
        self.stateFiveLabel.setObjectName("stateFiveLabel")
        self.stateSixLabel = QtWidgets.QLabel(self.autoFrame)
        self.stateSixLabel.setGeometry(QtCore.QRect(300, 160, 61, 31))
        self.stateSixLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.stateSixLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.stateSixLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stateSixLabel.setLineWidth(2)
        self.stateSixLabel.setObjectName("stateSixLabel")
        self.processLabel = QtWidgets.QLabel(self.autoFrame)
        self.processLabel.setGeometry(QtCore.QRect(80, 40, 211, 71))
        self.processLabel.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"color: rgb(0, 0, 0);")
        self.processLabel.setText("")
        self.processLabel.setObjectName("processLabel")
        self.manualFrame = QtWidgets.QFrame(self.centralwidget)
        self.manualFrame.setGeometry(QtCore.QRect(160, 200, 361, 221))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.manualFrame.setPalette(palette)
        self.manualFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.manualFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.manualFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.manualFrame.setLineWidth(2)
        self.manualFrame.setMidLineWidth(9)
        self.manualFrame.setObjectName("manualFrame")
        self.label_10 = QtWidgets.QLabel(self.manualFrame)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.manualFrame)
        self.label_11.setGeometry(QtCore.QRect(190, 70, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.velocityInputLabel = QtWidgets.QLineEdit(self.manualFrame)
        self.velocityInputLabel.setGeometry(QtCore.QRect(20, 70, 71, 31))
        self.velocityInputLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.velocityInputLabel.setObjectName("velocityInputLabel")
        self.sendVelocityButton = QtWidgets.QPushButton(self.manualFrame)
        self.sendVelocityButton.setGeometry(QtCore.QRect(100, 70, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sendVelocityButton.setFont(font)
        self.sendVelocityButton.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.sendVelocityButton.setObjectName("sendVelocityButton")
        self.upArrowButtonDrill = QtWidgets.QPushButton(self.manualFrame)
        self.upArrowButtonDrill.setGeometry(QtCore.QRect(190, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.upArrowButtonDrill.setFont(font)
        self.upArrowButtonDrill.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.upArrowButtonDrill.setObjectName("upArrowButtonDrill")
        self.upArrowButtonProbe = QtWidgets.QPushButton(self.manualFrame)
        self.upArrowButtonProbe.setGeometry(QtCore.QRect(280, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.upArrowButtonProbe.setFont(font)
        self.upArrowButtonProbe.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.upArrowButtonProbe.setObjectName("upArrowButtonProbe")
        self.downArrowButtonProbe = QtWidgets.QPushButton(self.manualFrame)
        self.downArrowButtonProbe.setGeometry(QtCore.QRect(280, 160, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.downArrowButtonProbe.setFont(font)
        self.downArrowButtonProbe.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.downArrowButtonProbe.setObjectName("downArrowButtonProbe")
        self.downArrowButtonDrill = QtWidgets.QPushButton(self.manualFrame)
        self.downArrowButtonDrill.setGeometry(QtCore.QRect(190, 160, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.downArrowButtonDrill.setFont(font)
        self.downArrowButtonDrill.setStyleSheet("\n"
"background-color: rgb(140, 140, 140);")
        self.downArrowButtonDrill.setObjectName("downArrowButtonDrill")
        self.label_16 = QtWidgets.QLabel(self.manualFrame)
        self.label_16.setGeometry(QtCore.QRect(280, 70, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.manualFrame)
        self.label_17.setGeometry(QtCore.QRect(110, 110, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.manualFrame)
        self.label_20.setGeometry(QtCore.QRect(110, 170, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.sensorFrame = QtWidgets.QFrame(self.centralwidget)
        self.sensorFrame.setGeometry(QtCore.QRect(0, 70, 161, 351))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.sensorFrame.setPalette(palette)
        self.sensorFrame.setStyleSheet("background-color: rgb(255, 102, 0);")
        self.sensorFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.sensorFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sensorFrame.setLineWidth(2)
        self.sensorFrame.setMidLineWidth(9)
        self.sensorFrame.setObjectName("sensorFrame")
        self.label_18 = QtWidgets.QLabel(self.sensorFrame)
        self.label_18.setGeometry(QtCore.QRect(4, 20, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.temperatureLcd = QtWidgets.QLCDNumber(self.sensorFrame)
        self.temperatureLcd.setGeometry(QtCore.QRect(20, 70, 61, 23))
        self.temperatureLcd.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.temperatureLcd.setObjectName("temperatureLcd")
        self.soilTemperatureLcd = QtWidgets.QLCDNumber(self.sensorFrame)
        self.soilTemperatureLcd.setGeometry(QtCore.QRect(20, 130, 61, 23))
        self.soilTemperatureLcd.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.soilTemperatureLcd.setObjectName("soilTemperatureLcd")
        self.humidityLcd = QtWidgets.QLCDNumber(self.sensorFrame)
        self.humidityLcd.setGeometry(QtCore.QRect(20, 190, 61, 23))
        self.humidityLcd.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.humidityLcd.setObjectName("humidityLcd")
        self.rpmLcd = QtWidgets.QLCDNumber(self.sensorFrame)
        self.rpmLcd.setGeometry(QtCore.QRect(20, 250, 61, 23))
        self.rpmLcd.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.rpmLcd.setObjectName("rpmLcd")
        self.label_6 = QtWidgets.QLabel(self.sensorFrame)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.sensorFrame)
        self.label_9.setGeometry(QtCore.QRect(20, 110, 121, 16))
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.sensorFrame)
        self.label_13.setGeometry(QtCore.QRect(20, 170, 81, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.sensorFrame)
        self.label_14.setGeometry(QtCore.QRect(20, 230, 31, 16))
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(self.sensorFrame)
        self.label_19.setGeometry(QtCore.QRect(20, 290, 81, 16))
        self.label_19.setObjectName("label_19")
        self.label_12 = QtWidgets.QLabel(self.sensorFrame)
        self.label_12.setGeometry(QtCore.QRect(90, 70, 41, 21))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.sensorFrame)
        self.label_15.setGeometry(QtCore.QRect(90, 130, 41, 21))
        self.label_15.setObjectName("label_15")
        self.upStateLabel = QtWidgets.QLabel(self.sensorFrame)
        self.upStateLabel.setGeometry(QtCore.QRect(10, 310, 31, 31))
        self.upStateLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.upStateLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.upStateLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upStateLabel.setLineWidth(2)
        self.upStateLabel.setObjectName("upStateLabel")
        self.stopStateLabel = QtWidgets.QLabel(self.sensorFrame)
        self.stopStateLabel.setGeometry(QtCore.QRect(40, 310, 41, 31))
        self.stopStateLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.stopStateLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.stopStateLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stopStateLabel.setLineWidth(2)
        self.stopStateLabel.setObjectName("stopStateLabel")
        self.downStateLabel = QtWidgets.QLabel(self.sensorFrame)
        self.downStateLabel.setGeometry(QtCore.QRect(80, 310, 51, 31))
        self.downStateLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.downStateLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.downStateLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downStateLabel.setLineWidth(2)
        self.downStateLabel.setObjectName("downStateLabel")
        self.label_22 = QtWidgets.QLabel(self.sensorFrame)
        self.label_22.setGeometry(QtCore.QRect(90, 190, 31, 21))
        self.label_22.setObjectName("label_22")
        probeGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(probeGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 22))
        self.menubar.setObjectName("menubar")
        probeGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(probeGui)
        self.statusbar.setObjectName("statusbar")
        probeGui.setStatusBar(self.statusbar)

        self.retranslateUi(probeGui)
        QtCore.QMetaObject.connectSlotsByName(probeGui)

    def retranslateUi(self, probeGui):
        _translate = QtCore.QCoreApplication.translate
        probeGui.setWindowTitle(_translate("probeGui", "Probe Panel"))
        self.manualControlRadio.setText(_translate("probeGui", "Manual"))
        self.autoControlRadio.setText(_translate("probeGui", "Auto"))
        self.label_8.setText(_translate("probeGui", "AUTO CONTROL"))
        self.startCycleButton.setText(_translate("probeGui", "START"))
        self.stopCycleButton.setText(_translate("probeGui", "STOP"))
        self.stateOneLabel.setText(_translate("probeGui", "STEP 1"))
        self.stateTwoLabel.setText(_translate("probeGui", "STEP2"))
        self.stateThreeLabel.setText(_translate("probeGui", "STEP 3"))
        self.stateFourLabel.setText(_translate("probeGui", "STEP 4"))
        self.stateFiveLabel.setText(_translate("probeGui", "STEP 5"))
        self.stateSixLabel.setText(_translate("probeGui", "STEP 6"))
        self.label_10.setText(_translate("probeGui", "MANUAL CONTROL"))
        self.label_11.setText(_translate("probeGui", "Drill"))
        self.sendVelocityButton.setText(_translate("probeGui", "SEND"))
        self.upArrowButtonDrill.setText(_translate("probeGui", "↑"))
        self.upArrowButtonProbe.setText(_translate("probeGui", "↑"))
        self.downArrowButtonProbe.setText(_translate("probeGui", "↓"))
        self.downArrowButtonDrill.setText(_translate("probeGui", "↓"))
        self.label_16.setText(_translate("probeGui", "Probe"))
        self.label_17.setText(_translate("probeGui", "Lifting"))
        self.label_20.setText(_translate("probeGui", "Lowering"))
        self.label_18.setText(_translate("probeGui", "SENSORS"))
        self.label_6.setText(_translate("probeGui", "Temperature"))
        self.label_9.setText(_translate("probeGui", "Soil Temperature"))
        self.label_13.setText(_translate("probeGui", "Humidity"))
        self.label_14.setText(_translate("probeGui", "RPM"))
        self.label_19.setText(_translate("probeGui", "State"))
        self.label_12.setText(_translate("probeGui", "[°C]"))
        self.label_15.setText(_translate("probeGui", "[°C]"))
        self.upStateLabel.setText(_translate("probeGui", "up"))
        self.stopStateLabel.setText(_translate("probeGui", "stop"))
        self.downStateLabel.setText(_translate("probeGui", "down"))
        self.label_22.setText(_translate("probeGui", "[%]"))
